### PR TITLE
fix: remove the worldseeder in run method of databaseSeeder 

### PR DESCRIPTION
**Pull request by darwinnatha**
J'ai commente le WorldSeeder qui causait probleme lors de l'execution du `php artisan db:seed`

### CODE REVIEW

**Comment by mckenziearts** [comment]
To remove this Seeder you need to complete uninstall the `nnjeim/world` package from composer. Drop all class `WorldSeeder` inside the `database/seeders` folder before remove the WorldSeeder class inside the `DatabaseSeeder` class

**Review by mckenziearts — CHANGES_REQUESTED** [review]
Remove the package not only the class

**Comment by darwinnatha** [comment]
It

> Remove the package not only the class


It's done

**Comment by mckenziearts** [comment]
The WorldSeeder class already exist. You have only remove the composer dependency and update the DatabaseSeeder class you don't complety uninstall the package

**Comment by darwinnatha** [comment]
Thank's it's done right now

**Comment by darwinnatha** [comment]
It's necessary to type `composer lint` ?

**Comment by mckenziearts** [comment]
Yes everytime

**Pull request merged**
